# Generated by Django 2.2 on 2020-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bingjixibie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bingjixibie', models.CharField(max_length=255, verbose_name='病机系别')),
            ],
            options={
                'verbose_name': '病机系别',
                'verbose_name_plural': '病机系别',
            },
        ),
        migrations.CreateModel(
            name='Zhibingjili',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('zhifaleibie', models.CharField(max_length=255, verbose_name='治法类别')),
                ('bingji_zhifa', models.CharField(max_length=255, verbose_name='病机-治法')),
                ('bingjixibie', models.CharField(max_length=255, verbose_name='病机系别')),
            ],
            options={
                'verbose_name': '致病机理',
                'verbose_name_plural': '致病机理',
            },
        ),
    ]
