# Generated by Django 2.2 on 2020-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bingzheng',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bingji_zhifa', models.CharField(max_length=5000)),
                ('shiyingzhenghou', models.TextField()),
                ('binglifenxi', models.TextField()),
                ('lifazufang', models.TextField()),
            ],
            options={
                'verbose_name': '病机-治法',
                'verbose_name_plural': '病机-治法',
            },
        ),
        migrations.CreateModel(
            name='Lifang',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bingji_zhifa', models.CharField(max_length=255)),
                ('lifangming', models.CharField(max_length=255)),
                ('zhuzhi', models.TextField()),
                ('zhengxi', models.TextField()),
                ('bingji', models.TextField()),
                ('zhifa', models.TextField()),
            ],
            options={
                'verbose_name': '例方',
                'verbose_name_plural': '例方',
            },
        ),
        migrations.AlterModelOptions(
            name='zhibingjili',
            options={'verbose_name': '治法类别', 'verbose_name_plural': '治法类别'},
        ),
        migrations.AlterField(
            model_name='bingjixibie',
            name='bingjixibie',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zhibingjili',
            name='bingji_zhifa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zhibingjili',
            name='bingjixibie',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zhibingjili',
            name='zhifaleibie',
            field=models.CharField(max_length=255),
        ),
    ]
